version: '1.0'

stages:
  - clone
  - build

steps:
  main_clone:
    title: Cloning main repository...
    stage: "clone"
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
  build-stage:
    title: Building Docker Image
    type: build
    stage: "build"
    image_name: ob-release
    working_directory: ./
    tag: latest
    dockerfile: Dockerfile
    when:
      branch:
        only:
          - master